"""V8

Revision ID: 078398ea685e
Revises: 7cbf75361436
Create Date: 2018-01-18 13:17:41.935640

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '078398ea685e'
down_revision = '7cbf75361436'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('salary_high', sa.Integer(), nullable=False))
    op.add_column('job', sa.Column('salary_low', sa.Integer(), nullable=False))
    op.drop_column('job', 'salary_range')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('salary_range', mysql.VARCHAR(collation='utf8_unicode_ci', length=128), nullable=True))
    op.drop_column('job', 'salary_low')
    op.drop_column('job', 'salary_high')
    # ### end Alembic commands ###
