"""V11

Revision ID: 3b8c054d2114
Revises: 69f7c1e36e1a
Create Date: 2018-01-23 12:49:47.612349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b8c054d2114'
down_revision = '69f7c1e36e1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery', sa.Column('job_name', sa.String(length=32), nullable=True))
    op.add_column('delivery', sa.Column('user_realname', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('delivery', 'user_realname')
    op.drop_column('delivery', 'job_name')
    # ### end Alembic commands ###
