"""V10

Revision ID: 69f7c1e36e1a
Revises: 9c83d0e0d5ed
Create Date: 2018-01-23 12:05:25.954903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69f7c1e36e1a'
down_revision = '9c83d0e0d5ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'delivery', 'company', ['company_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'delivery', type_='foreignkey')
    op.drop_column('delivery', 'company_id')
    # ### end Alembic commands ###
