"""V6

Revision ID: 7cbf75361436
Revises: 8212c6546aff
Create Date: 2018-01-18 10:32:19.945350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cbf75361436'
down_revision = '8212c6546aff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery',
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('response', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resume',
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_job',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE')
    )
    op.create_table('edu_experience',
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('begin_at', sa.DateTime(), nullable=True),
    sa.Column('end_at', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('school', sa.String(length=32), nullable=False),
    sa.Column('major', sa.String(length=32), nullable=False),
    sa.Column('degree', sa.String(length=16), nullable=True),
    sa.Column('resume_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['resume.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_experience',
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('begin_at', sa.DateTime(), nullable=True),
    sa.Column('end_at', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('used_company', sa.String(length=32), nullable=False),
    sa.Column('city', sa.String(length=32), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['resume.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_experience',
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('begin_at', sa.DateTime(), nullable=True),
    sa.Column('end_at', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=True),
    sa.Column('technologys', sa.String(length=64), nullable=True),
    sa.Column('resume_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['resume.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('company', sa.Column('about', sa.String(length=1024), nullable=True))
    op.add_column('company', sa.Column('tags', sa.String(length=128), nullable=True))
    op.add_column('job', sa.Column('id_open', sa.Boolean(), nullable=True))
    op.add_column('job', sa.Column('is_fulltime', sa.Boolean(), nullable=True))
    op.add_column('job', sa.Column('tags', sa.String(length=128), nullable=True))
    op.add_column('job', sa.Column('view_count', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('phone', sa.String(length=11), nullable=True))
    op.add_column('user', sa.Column('resume_url', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('work_years', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'work_years')
    op.drop_column('user', 'resume_url')
    op.drop_column('user', 'phone')
    op.drop_column('job', 'view_count')
    op.drop_column('job', 'tags')
    op.drop_column('job', 'is_fulltime')
    op.drop_column('job', 'id_open')
    op.drop_column('company', 'tags')
    op.drop_column('company', 'about')
    op.drop_table('project_experience')
    op.drop_table('job_experience')
    op.drop_table('edu_experience')
    op.drop_table('user_job')
    op.drop_table('resume')
    op.drop_table('delivery')
    # ### end Alembic commands ###
