"""V9

Revision ID: 9c83d0e0d5ed
Revises: 078398ea685e
Create Date: 2018-01-18 14:08:31.459707

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9c83d0e0d5ed'
down_revision = '078398ea685e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('is_open', sa.Boolean(), nullable=True))
    op.drop_column('job', 'id_open')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('id_open', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('job', 'is_open')
    # ### end Alembic commands ###
