"""simple

Revision ID: bdd1c2253762
Revises: 8607980e2287
Create Date: 2018-01-05 15:02:08.418398

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bdd1c2253762'
down_revision = '8607980e2287'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=256), nullable=False))
    op.drop_column('user', '_password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('_password', mysql.VARCHAR(collation='utf8_unicode_ci', length=256), nullable=False))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
